module.exports = {
    CONTINUE: "continue",
    SWITCHING_PROTOCOLS: "switching protocols",
    PROCESSING: "processing",
    EARLY_HINTS: "early hints",
    OK: "ok",
    CREATED: "created",
    ACCEPTED: "accepted",
    NON_AUTHORITATIVE_INFORMATION: "non-authoritative information",
    NO_CONTENT: "no content",
    RESET_CONTENT: "reset content",
    PARTIAL_CONTENT: "partial content",
    MULTI_STATUS: "multi-status",
    MULTIPLE_CHOICES: "multiple choices",
    MOVED_PERMANENTLY: "moved permanently",
    MOVED_TEMPORARILY: "moved temporarily",
    SEE_OTHER: "see other",
    NOT_MODIFIED: "not modified",
    USE_PROXY: "use proxy",
    TEMPORARY_REDIRECT: "temporary redirect",
    PERMANENT_REDIRECT: "permanent redirect",
    BAD_REQUEST: "bad request",
    UNAUTHORIZED: "unauthorized",
    PAYMENT_REQUIRED: "payment required",
    FORBIDDEN: "forbidden",
    NOT_FOUND: "not found",
    METHOD_NOT_ALLOWED: "method not allowed",
    NOT_ACCEPTABLE: "not acceptable",
    PROXY_AUTHENTICATION_REQUIRED: "proxy authentication required",
    REQUEST_TIMEOUT: "request timeout",
    CONFLICT: "conflict",
    GONE: "gone",
    LENGTH_REQUIRED: "length required",
    PRECONDITION_FAILED: "precondition failed",
    REQUEST_TOO_LONG: "request too long",
    REQUEST_URI_TOO_LONG: "request-uri too long",
    UNSUPPORTED_MEDIA_TYPE: "unsupported media type",
    REQUESTED_RANGE_NOT_SATISFIABLE: "requested range not satisfiable",
    EXPECTATION_FAILED: "expectation failed",
    IM_A_TEAPOT: "i'm a teapot",
    INSUFFICIENT_SPACE_ON_RESOURCE: "insufficient space on resource",
    METHOD_FAILURE: "method failure",
    MISDIRECTED_REQUEST: "misdirected request",
    UNPROCESSABLE_ENTITY: "unprocessable entity",
    LOCKED: "locked",
    FAILED_DEPENDENCY: "failed dependency",
    UPGRADE_REQUIRED: "upgrade required",
    PRECONDITION_REQUIRED: "precondition required",
    TOO_MANY_REQUESTS: "too many requests",
    REQUEST_HEADER_FIELDS_TOO_LARGE: "request header fields too large",
    UNAVAILABLE_FOR_LEGAL_REASONS: "unavailable for legal reasons",
    INTERNAL_SERVER_ERROR: "internal server error",
    NOT_IMPLEMENTED: "not implemented",
    BAD_GATEWAY: "bad gateway",
    SERVICE_UNAVAILABLE: "service unavailable",
    GATEWAY_TIMEOUT: "gateway timeout",
    HTTP_VERSION_NOT_SUPPORTED: "http version not supported",
    INSUFFICIENT_STORAGE: "insufficient storage",
    LOOP_DETECTED: "loop detected",
    NOT_EXTENDED: "not extended",
    NETWORK_AUTHENTICATION_REQUIRED: "network authentication required"
};
